"""C. elegans developmental stage"""

import requests
from pydantic import BaseModel, ConfigDict

from biodata_models.registries import Registry

"""C. elegans developmental stage"""


class CElegansDevelopmentalStageModel(BaseModel):
    """Base model for C. elegans developmental stage"""

    model_config = ConfigDict(frozen=True)
    name: str
    registry: Registry
    registry_identifier: str


def search_wbls_exact_match(class_name):
    """Pull the exact name match from the WBLS ontology

    Parameters
    ----------
    class_name : str
        Name of class

    Returns
    -------
    list

    Raises
    ------
    Exception
        OLS query failed on any status code other than 200
    """
    base_url = "https://www.ebi.ac.uk/ols4/api/search"
    params = {
        "q": class_name,
        "ontology": "wbls",  # Specify the ontology
        "type": "class",  # Search for classes
    }
    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        results = response.json()
        # Extract terms with exact label match
        exact_matches = [
            {
                "iri": entry["iri"],
                "label": entry["label"],
            }
            for entry in results.get("response", {}).get("docs", [])
            if entry["label"].lower() == class_name.lower()
        ]
        return exact_matches
    else:
        raise Exception(f"OLS query failed: {response.status_code}, {response.text}")


def get_wbls_id(class_name):
    """Get the WBLS ID for a given class name

    Parameters
    ----------
    class_name : str

    Returns
    -------
    int
    """
    results = search_wbls_exact_match(class_name)

    if results:
        return results[0]["iri"].split("_")[1]
    else:
        return None


class CElegansDevelopmentalStageMeta(type):
    """Meta class for CElegansDevelopmentalStage groups"""

    def __getattribute__(cls, name):
        """Custom get attribute function, validates developmental stage names against external WBLS registry

        Parameters
        ----------
        name : str
            Attribute name

        Raises
        ------
        ValueError
            Name not found in the WBLS registry
        """

        # bypass
        if name.startswith("__"):
            return object.__getattribute__(cls, name)

        class_dict = object.__getattribute__(cls, "__dict__")

        if name in class_dict:
            original_name = super().__getattribute__(name)

            wbls_id = get_wbls_id(original_name)

            if wbls_id:
                return CElegansDevelopmentalStageModel(
                    name=original_name,
                    registry=Registry.WBLS,
                    registry_identifier=wbls_id,
                )
            else:
                raise ValueError(f"Could not find WBLS ID for {original_name}")

        # second bypass for defined values
        return super().__getattribute__(name)


class CElegansDevelopmentalStage(metaclass=CElegansDevelopmentalStageMeta):
    """C. elegans developmental stage"""

    _1_MIN_POST_FIRST_CLEAVAGE_CE = "1 min post first-cleavage Ce"
    _1_CELL_EMBRYO_CE = "1-cell embryo Ce"
    _1_DAY_POST_L4_ADULT_HERMAPHRODITE_CE = "1-day post-L4 adult hermaphrodite Ce"
    _1_5_FOLD_EMBRYO_CE = "1.5-fold embryo Ce"
    _10_MIN_POST_FIRST_CLEAVAGE_CE = "10 min post first-cleavage Ce"
    _10_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "10-days post-L4 adult hermaphrodite Ce"
    _100_MIN_POST_FIRST_CLEAVAGE_CE = "100 min post first-cleavage Ce"
    _101_MIN_POST_FIRST_CLEAVAGE_CE = "101 min post first-cleavage Ce"
    _102_MIN_POST_FIRST_CLEAVAGE_CE = "102 min post first-cleavage Ce"
    _103_MIN_POST_FIRST_CLEAVAGE_CE = "103 min post first-cleavage Ce"
    _104_MIN_POST_FIRST_CLEAVAGE_CE = "104 min post first-cleavage Ce"
    _105_MIN_POST_FIRST_CLEAVAGE_CE = "105 min post first-cleavage Ce"
    _106_MIN_POST_FIRST_CLEAVAGE_CE = "106 min post first-cleavage Ce"
    _107_MIN_POST_FIRST_CLEAVAGE_CE = "107 min post first-cleavage Ce"
    _108_MIN_POST_FIRST_CLEAVAGE_CE = "108 min post first-cleavage Ce"
    _109_MIN_POST_FIRST_CLEAVAGE_CE = "109 min post first-cleavage Ce"
    _11_MIN_POST_FIRST_CLEAVAGE_CE = "11 min post first-cleavage Ce"
    _11_15_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "11-15 days post-L4 adult hermaphrodite Ce"
    _11_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "11-days post-L4 adult hermaphrodite Ce"
    _110_MIN_POST_FIRST_CLEAVAGE_CE = "110 min post first-cleavage Ce"
    _111_MIN_POST_FIRST_CLEAVAGE_CE = "111 min post first-cleavage Ce"
    _112_MIN_POST_FIRST_CLEAVAGE_CE = "112 min post first-cleavage Ce"
    _113_MIN_POST_FIRST_CLEAVAGE_CE = "113 min post first-cleavage Ce"
    _114_MIN_POST_FIRST_CLEAVAGE_CE = "114 min post first-cleavage Ce"
    _115_MIN_POST_FIRST_CLEAVAGE_CE = "115 min post first-cleavage Ce"
    _116_MIN_POST_FIRST_CLEAVAGE_CE = "116 min post first-cleavage Ce"
    _117_MIN_POST_FIRST_CLEAVAGE_CE = "117 min post first-cleavage Ce"
    _118_MIN_POST_FIRST_CLEAVAGE_CE = "118 min post first-cleavage Ce"
    _119_MIN_POST_FIRST_CLEAVAGE_CE = "119 min post first-cleavage Ce"
    _12_MIN_POST_FIRST_CLEAVAGE_CE = "12 min post first-cleavage Ce"
    _12_CELL_EMBRYO_CE = "12-cell embryo Ce"
    _12_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "12-days post-L4 adult hermaphrodite Ce"
    _120_MIN_POST_FIRST_CLEAVAGE_CE = "120 min post first-cleavage Ce"
    _121_MIN_POST_FIRST_CLEAVAGE_CE = "121 min post first-cleavage Ce"
    _122_MIN_POST_FIRST_CLEAVAGE_CE = "122 min post first-cleavage Ce"
    _123_MIN_POST_FIRST_CLEAVAGE_CE = "123 min post first-cleavage Ce"
    _124_MIN_POST_FIRST_CLEAVAGE_CE = "124 min post first-cleavage Ce"
    _125_MIN_POST_FIRST_CLEAVAGE_CE = "125 min post first-cleavage Ce"
    _126_MIN_POST_FIRST_CLEAVAGE_CE = "126 min post first-cleavage Ce"
    _127_MIN_POST_FIRST_CLEAVAGE_CE = "127 min post first-cleavage Ce"
    _128_MIN_POST_FIRST_CLEAVAGE_CE = "128 min post first-cleavage Ce"
    _129_MIN_POST_FIRST_CLEAVAGE_CE = "129 min post first-cleavage Ce"
    _13_MIN_POST_FIRST_CLEAVAGE_CE = "13 min post first-cleavage Ce"
    _13_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "13-days post-L4 adult hermaphrodite Ce"
    _130_MIN_POST_FIRST_CLEAVAGE_CE = "130 min post first-cleavage Ce"
    _131_MIN_POST_FIRST_CLEAVAGE_CE = "131 min post first-cleavage Ce"
    _132_MIN_POST_FIRST_CLEAVAGE_CE = "132 min post first-cleavage Ce"
    _133_MIN_POST_FIRST_CLEAVAGE_CE = "133 min post first-cleavage Ce"
    _134_MIN_POST_FIRST_CLEAVAGE_CE = "134 min post first-cleavage Ce"
    _135_MIN_POST_FIRST_CLEAVAGE_CE = "135 min post first-cleavage Ce"
    _136_MIN_POST_FIRST_CLEAVAGE_CE = "136 min post first-cleavage Ce"
    _137_MIN_POST_FIRST_CLEAVAGE_CE = "137 min post first-cleavage Ce"
    _138_MIN_POST_FIRST_CLEAVAGE_CE = "138 min post first-cleavage Ce"
    _139_MIN_POST_FIRST_CLEAVAGE_CE = "139 min post first-cleavage Ce"
    _14_MIN_POST_FIRST_CLEAVAGE_CE = "14 min post first-cleavage Ce"
    _14_CELL_EMBRYO_CE = "14-cell embryo Ce"
    _14_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "14-days post-L4 adult hermaphrodite Ce"
    _140_MIN_POST_FIRST_CLEAVAGE_CE = "140 min post first-cleavage Ce"
    _141_MIN_POST_FIRST_CLEAVAGE_CE = "141 min post first-cleavage Ce"
    _142_MIN_POST_FIRST_CLEAVAGE_CE = "142 min post first-cleavage Ce"
    _143_MIN_POST_FIRST_CLEAVAGE_CE = "143 min post first-cleavage Ce"
    _144_MIN_POST_FIRST_CLEAVAGE_CE = "144 min post first-cleavage Ce"
    _145_MIN_POST_FIRST_CLEAVAGE_CE = "145 min post first-cleavage Ce"
    _146_MIN_POST_FIRST_CLEAVAGE_CE = "146 min post first-cleavage Ce"
    _147_MIN_POST_FIRST_CLEAVAGE_CE = "147 min post first-cleavage Ce"
    _148_MIN_POST_FIRST_CLEAVAGE_CE = "148 min post first-cleavage Ce"
    _149_MIN_POST_FIRST_CLEAVAGE_CE = "149 min post first-cleavage Ce"
    _15_MIN_POST_FIRST_CLEAVAGE_CE = "15 min post first-cleavage Ce"
    _15_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "15-days post-L4 adult hermaphrodite Ce"
    _150_MIN_POST_FIRST_CLEAVAGE_CE = "150 min post first-cleavage Ce"
    _151_MIN_POST_FIRST_CLEAVAGE_CE = "151 min post first-cleavage Ce"
    _152_MIN_POST_FIRST_CLEAVAGE_CE = "152 min post first-cleavage Ce"
    _153_MIN_POST_FIRST_CLEAVAGE_CE = "153 min post first-cleavage Ce"
    _154_MIN_POST_FIRST_CLEAVAGE_CE = "154 min post first-cleavage Ce"
    _155_MIN_POST_FIRST_CLEAVAGE_CE = "155 min post first-cleavage Ce"
    _156_MIN_POST_FIRST_CLEAVAGE_CE = "156 min post first-cleavage Ce"
    _157_MIN_POST_FIRST_CLEAVAGE_CE = "157 min post first-cleavage Ce"
    _158_MIN_POST_FIRST_CLEAVAGE_CE = "158 min post first-cleavage Ce"
    _159_MIN_POST_FIRST_CLEAVAGE_CE = "159 min post first-cleavage Ce"
    _16_MIN_POST_FIRST_CLEAVAGE_CE = "16 min post first-cleavage Ce"
    _16_18_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "16-18 days post-L4 adult hermaphrodite Ce"
    _160_MIN_POST_FIRST_CLEAVAGE_CE = "160 min post first-cleavage Ce"
    _161_MIN_POST_FIRST_CLEAVAGE_CE = "161 min post first-cleavage Ce"
    _162_MIN_POST_FIRST_CLEAVAGE_CE = "162 min post first-cleavage Ce"
    _163_MIN_POST_FIRST_CLEAVAGE_CE = "163 min post first-cleavage Ce"
    _164_MIN_POST_FIRST_CLEAVAGE_CE = "164 min post first-cleavage Ce"
    _165_MIN_POST_FIRST_CLEAVAGE_CE = "165 min post first-cleavage Ce"
    _166_MIN_POST_FIRST_CLEAVAGE_CE = "166 min post first-cleavage Ce"
    _167_MIN_POST_FIRST_CLEAVAGE_CE = "167 min post first-cleavage Ce"
    _168_MIN_POST_FIRST_CLEAVAGE_CE = "168 min post first-cleavage Ce"
    _169_MIN_POST_FIRST_CLEAVAGE_CE = "169 min post first-cleavage Ce"
    _17_MIN_POST_FIRST_CLEAVAGE_CE = "17 min post first-cleavage Ce"
    _170_MIN_POST_FIRST_CLEAVAGE_CE = "170 min post first-cleavage Ce"
    _171_MIN_POST_FIRST_CLEAVAGE_CE = "171 min post first-cleavage Ce"
    _172_MIN_POST_FIRST_CLEAVAGE_CE = "172 min post first-cleavage Ce"
    _173_MIN_POST_FIRST_CLEAVAGE_CE = "173 min post first-cleavage Ce"
    _174_MIN_POST_FIRST_CLEAVAGE_CE = "174 min post first-cleavage Ce"
    _175_MIN_POST_FIRST_CLEAVAGE_CE = "175 min post first-cleavage Ce"
    _176_MIN_POST_FIRST_CLEAVAGE_CE = "176 min post first-cleavage Ce"
    _177_MIN_POST_FIRST_CLEAVAGE_CE = "177 min post first-cleavage Ce"
    _178_MIN_POST_FIRST_CLEAVAGE_CE = "178 min post first-cleavage Ce"
    _179_MIN_POST_FIRST_CLEAVAGE_CE = "179 min post first-cleavage Ce"
    _18_MIN_POST_FIRST_CLEAVAGE_CE = "18 min post first-cleavage Ce"
    _180_MIN_POST_FIRST_CLEAVAGE_CE = "180 min post first-cleavage Ce"
    _181_MIN_POST_FIRST_CLEAVAGE_CE = "181 min post first-cleavage Ce"
    _182_MIN_POST_FIRST_CLEAVAGE_CE = "182 min post first-cleavage Ce"
    _183_MIN_POST_FIRST_CLEAVAGE_CE = "183 min post first-cleavage Ce"
    _184_MIN_POST_FIRST_CLEAVAGE_CE = "184 min post first-cleavage Ce"
    _185_MIN_POST_FIRST_CLEAVAGE_CE = "185 min post first-cleavage Ce"
    _186_MIN_POST_FIRST_CLEAVAGE_CE = "186 min post first-cleavage Ce"
    _187_MIN_POST_FIRST_CLEAVAGE_CE = "187 min post first-cleavage Ce"
    _188_MIN_POST_FIRST_CLEAVAGE_CE = "188 min post first-cleavage Ce"
    _189_MIN_POST_FIRST_CLEAVAGE_CE = "189 min post first-cleavage Ce"
    _19_MIN_POST_FIRST_CLEAVAGE_CE = "19 min post first-cleavage Ce"
    _190_MIN_POST_FIRST_CLEAVAGE_CE = "190 min post first-cleavage Ce"
    _190_CELLS_EMBRYO_CE = "190-cells embryo Ce"
    _191_MIN_POST_FIRST_CLEAVAGE_CE = "191 min post first-cleavage Ce"
    _192_MIN_POST_FIRST_CLEAVAGE_CE = "192 min post first-cleavage Ce"
    _193_MIN_POST_FIRST_CLEAVAGE_CE = "193 min post first-cleavage Ce"
    _194_MIN_POST_FIRST_CLEAVAGE_CE = "194 min post first-cleavage Ce"
    _195_MIN_POST_FIRST_CLEAVAGE_CE = "195 min post first-cleavage Ce"
    _196_MIN_POST_FIRST_CLEAVAGE_CE = "196 min post first-cleavage Ce"
    _197_MIN_POST_FIRST_CLEAVAGE_CE = "197 min post first-cleavage Ce"
    _198_MIN_POST_FIRST_CLEAVAGE_CE = "198 min post first-cleavage Ce"
    _199_MIN_POST_FIRST_CLEAVAGE_CE = "199 min post first-cleavage Ce"
    _2_MIN_POST_FIRST_CLEAVAGE_CE = "2 min post first-cleavage Ce"
    _2_CELL_EMBRYO_CE = "2-cell embryo Ce"
    _2_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "2-days post-L4 adult hermaphrodite Ce"
    _2_FOLD_EMBRYO_CE = "2-fold embryo Ce"
    _20_MIN_POST_FIRST_CLEAVAGE_CE = "20 min post first-cleavage Ce"
    _20_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "20-days post-L4 adult hermaphrodite Ce"
    _200_MIN_POST_FIRST_CLEAVAGE_CE = "200 min post first-cleavage Ce"
    _201_MIN_POST_FIRST_CLEAVAGE_CE = "201 min post first-cleavage Ce"
    _202_MIN_POST_FIRST_CLEAVAGE_CE = "202 min post first-cleavage Ce"
    _203_MIN_POST_FIRST_CLEAVAGE_CE = "203 min post first-cleavage Ce"
    _204_MIN_POST_FIRST_CLEAVAGE_CE = "204 min post first-cleavage Ce"
    _205_MIN_POST_FIRST_CLEAVAGE_CE = "205 min post first-cleavage Ce"
    _206_MIN_POST_FIRST_CLEAVAGE_CE = "206 min post first-cleavage Ce"
    _207_MIN_POST_FIRST_CLEAVAGE_CE = "207 min post first-cleavage Ce"
    _208_MIN_POST_FIRST_CLEAVAGE_CE = "208 min post first-cleavage Ce"
    _209_MIN_POST_FIRST_CLEAVAGE_CE = "209 min post first-cleavage Ce"
    _21_MIN_POST_FIRST_CLEAVAGE_CE = "21 min post first-cleavage Ce"
    _210_MIN_POST_FIRST_CLEAVAGE_CE = "210 min post first-cleavage Ce"
    _211_MIN_POST_FIRST_CLEAVAGE_CE = "211 min post first-cleavage Ce"
    _212_MIN_POST_FIRST_CLEAVAGE_CE = "212 min post first-cleavage Ce"
    _213_MIN_POST_FIRST_CLEAVAGE_CE = "213 min post first-cleavage Ce"
    _214_MIN_POST_FIRST_CLEAVAGE_CE = "214 min post first-cleavage Ce"
    _215_MIN_POST_FIRST_CLEAVAGE_CE = "215 min post first-cleavage Ce"
    _216_MIN_POST_FIRST_CLEAVAGE_CE = "216 min post first-cleavage Ce"
    _217_MIN_POST_FIRST_CLEAVAGE_CE = "217 min post first-cleavage Ce"
    _218_MIN_POST_FIRST_CLEAVAGE_CE = "218 min post first-cleavage Ce"
    _219_MIN_POST_FIRST_CLEAVAGE_CE = "219 min post first-cleavage Ce"
    _22_MIN_POST_FIRST_CLEAVAGE_CE = "22 min post first-cleavage Ce"
    _220_MIN_POST_FIRST_CLEAVAGE_CE = "220 min post first-cleavage Ce"
    _221_MIN_POST_FIRST_CLEAVAGE_CE = "221 min post first-cleavage Ce"
    _222_MIN_POST_FIRST_CLEAVAGE_CE = "222 min post first-cleavage Ce"
    _223_MIN_POST_FIRST_CLEAVAGE_CE = "223 min post first-cleavage Ce"
    _224_MIN_POST_FIRST_CLEAVAGE_CE = "224 min post first-cleavage Ce"
    _225_MIN_POST_FIRST_CLEAVAGE_CE = "225 min post first-cleavage Ce"
    _226_MIN_POST_FIRST_CLEAVAGE_CE = "226 min post first-cleavage Ce"
    _227_MIN_POST_FIRST_CLEAVAGE_CE = "227 min post first-cleavage Ce"
    _228_MIN_POST_FIRST_CLEAVAGE_CE = "228 min post first-cleavage Ce"
    _229_MIN_POST_FIRST_CLEAVAGE_CE = "229 min post first-cleavage Ce"
    _23_MIN_POST_FIRST_CLEAVAGE_CE = "23 min post first-cleavage Ce"
    _230_MIN_POST_FIRST_CLEAVAGE_CE = "230 min post first-cleavage Ce"
    _231_MIN_POST_FIRST_CLEAVAGE_CE = "231 min post first-cleavage Ce"
    _232_MIN_POST_FIRST_CLEAVAGE_CE = "232 min post first-cleavage Ce"
    _233_MIN_POST_FIRST_CLEAVAGE_CE = "233 min post first-cleavage Ce"
    _234_MIN_POST_FIRST_CLEAVAGE_CE = "234 min post first-cleavage Ce"
    _235_MIN_POST_FIRST_CLEAVAGE_CE = "235 min post first-cleavage Ce"
    _236_MIN_POST_FIRST_CLEAVAGE_CE = "236 min post first-cleavage Ce"
    _237_MIN_POST_FIRST_CLEAVAGE_CE = "237 min post first-cleavage Ce"
    _238_MIN_POST_FIRST_CLEAVAGE_CE = "238 min post first-cleavage Ce"
    _239_MIN_POST_FIRST_CLEAVAGE_CE = "239 min post first-cleavage Ce"
    _24_HR_SCHISTOSOMULUM = "24 hr schistosomulum"
    _24_MIN_POST_FIRST_CLEAVAGE_CE = "24 min post first-cleavage Ce"
    _24_CELL_EMBRYO_CE = "24-cell embryo Ce"
    _240_MIN_POST_FIRST_CLEAVAGE_CE = "240 min post first-cleavage Ce"
    _241_MIN_POST_FIRST_CLEAVAGE_CE = "241 min post first-cleavage Ce"
    _242_MIN_POST_FIRST_CLEAVAGE_CE = "242 min post first-cleavage Ce"
    _243_MIN_POST_FIRST_CLEAVAGE_CE = "243 min post first-cleavage Ce"
    _244_MIN_POST_FIRST_CLEAVAGE_CE = "244 min post first-cleavage Ce"
    _245_MIN_POST_FIRST_CLEAVAGE_CE = "245 min post first-cleavage Ce"
    _246_MIN_POST_FIRST_CLEAVAGE_CE = "246 min post first-cleavage Ce"
    _247_MIN_POST_FIRST_CLEAVAGE_CE = "247 min post first-cleavage Ce"
    _248_MIN_POST_FIRST_CLEAVAGE_CE = "248 min post first-cleavage Ce"
    _249_MIN_POST_FIRST_CLEAVAGE_CE = "249 min post first-cleavage Ce"
    _25_MIN_POST_FIRST_CLEAVAGE_CE = "25 min post first-cleavage Ce"
    _250_MIN_POST_FIRST_CLEAVAGE_CE = "250 min post first-cleavage Ce"
    _251_MIN_POST_FIRST_CLEAVAGE_CE = "251 min post first-cleavage Ce"
    _252_MIN_POST_FIRST_CLEAVAGE_CE = "252 min post first-cleavage Ce"
    _253_MIN_POST_FIRST_CLEAVAGE_CE = "253 min post first-cleavage Ce"
    _254_MIN_POST_FIRST_CLEAVAGE_CE = "254 min post first-cleavage Ce"
    _255_MIN_POST_FIRST_CLEAVAGE_CE = "255 min post first-cleavage Ce"
    _256_MIN_POST_FIRST_CLEAVAGE_CE = "256 min post first-cleavage Ce"
    _257_MIN_POST_FIRST_CLEAVAGE_CE = "257 min post first-cleavage Ce"
    _258_MIN_POST_FIRST_CLEAVAGE_CE = "258 min post first-cleavage Ce"
    _259_MIN_POST_FIRST_CLEAVAGE_CE = "259 min post first-cleavage Ce"
    _26_MIN_POST_FIRST_CLEAVAGE_CE = "26 min post first-cleavage Ce"
    _260_MIN_POST_FIRST_CLEAVAGE_CE = "260 min post first-cleavage Ce"
    _261_MIN_POST_FIRST_CLEAVAGE_CE = "261 min post first-cleavage Ce"
    _262_MIN_POST_FIRST_CLEAVAGE_CE = "262 min post first-cleavage Ce"
    _263_MIN_POST_FIRST_CLEAVAGE_CE = "263 min post first-cleavage Ce"
    _264_MIN_POST_FIRST_CLEAVAGE_CE = "264 min post first-cleavage Ce"
    _265_MIN_POST_FIRST_CLEAVAGE_CE = "265 min post first-cleavage Ce"
    _266_MIN_POST_FIRST_CLEAVAGE_CE = "266 min post first-cleavage Ce"
    _267_MIN_POST_FIRST_CLEAVAGE_CE = "267 min post first-cleavage Ce"
    _268_MIN_POST_FIRST_CLEAVAGE_CE = "268 min post first-cleavage Ce"
    _269_MIN_POST_FIRST_CLEAVAGE_CE = "269 min post first-cleavage Ce"
    _27_MIN_POST_FIRST_CLEAVAGE_CE = "27 min post first-cleavage Ce"
    _270_MIN_POST_FIRST_CLEAVAGE_CE = "270 min post first-cleavage Ce"
    _271_MIN_POST_FIRST_CLEAVAGE_CE = "271 min post first-cleavage Ce"
    _272_MIN_POST_FIRST_CLEAVAGE_CE = "272 min post first-cleavage Ce"
    _273_MIN_POST_FIRST_CLEAVAGE_CE = "273 min post first-cleavage Ce"
    _274_MIN_POST_FIRST_CLEAVAGE_CE = "274 min post first-cleavage Ce"
    _275_MIN_POST_FIRST_CLEAVAGE_CE = "275 min post first-cleavage Ce"
    _276_MIN_POST_FIRST_CLEAVAGE_CE = "276 min post first-cleavage Ce"
    _277_MIN_POST_FIRST_CLEAVAGE_CE = "277 min post first-cleavage Ce"
    _278_MIN_POST_FIRST_CLEAVAGE_CE = "278 min post first-cleavage Ce"
    _279_MIN_POST_FIRST_CLEAVAGE_CE = "279 min post first-cleavage Ce"
    _28_MIN_POST_FIRST_CLEAVAGE_CE = "28 min post first-cleavage Ce"
    _28_CELL_EMBRYO_CE = "28-cell embryo Ce"
    _280_MIN_POST_FIRST_CLEAVAGE_CE = "280 min post first-cleavage Ce"
    _281_MIN_POST_FIRST_CLEAVAGE_CE = "281 min post first-cleavage Ce"
    _282_MIN_POST_FIRST_CLEAVAGE_CE = "282 min post first-cleavage Ce"
    _283_MIN_POST_FIRST_CLEAVAGE_CE = "283 min post first-cleavage Ce"
    _284_MIN_POST_FIRST_CLEAVAGE_CE = "284 min post first-cleavage Ce"
    _285_MIN_POST_FIRST_CLEAVAGE_CE = "285 min post first-cleavage Ce"
    _286_MIN_POST_FIRST_CLEAVAGE_CE = "286 min post first-cleavage Ce"
    _287_MIN_POST_FIRST_CLEAVAGE_CE = "287 min post first-cleavage Ce"
    _288_MIN_POST_FIRST_CLEAVAGE_CE = "288 min post first-cleavage Ce"
    _289_MIN_POST_FIRST_CLEAVAGE_CE = "289 min post first-cleavage Ce"
    _29_MIN_POST_FIRST_CLEAVAGE_CE = "29 min post first-cleavage Ce"
    _290_MIN_POST_FIRST_CLEAVAGE_CE = "290 min post first-cleavage Ce"
    _291_MIN_POST_FIRST_CLEAVAGE_CE = "291 min post first-cleavage Ce"
    _292_MIN_POST_FIRST_CLEAVAGE_CE = "292 min post first-cleavage Ce"
    _293_MIN_POST_FIRST_CLEAVAGE_CE = "293 min post first-cleavage Ce"
    _294_MIN_POST_FIRST_CLEAVAGE_CE = "294 min post first-cleavage Ce"
    _295_MIN_POST_FIRST_CLEAVAGE_CE = "295 min post first-cleavage Ce"
    _296_MIN_POST_FIRST_CLEAVAGE_CE = "296 min post first-cleavage Ce"
    _297_MIN_POST_FIRST_CLEAVAGE_CE = "297 min post first-cleavage Ce"
    _298_MIN_POST_FIRST_CLEAVAGE_CE = "298 min post first-cleavage Ce"
    _299_MIN_POST_FIRST_CLEAVAGE_CE = "299 min post first-cleavage Ce"
    _3_HR_SCHISTOSOMULUM = "3 hr schistosomulum"
    _3_MIN_POST_FIRST_CLEAVAGE_CE = "3 min post first-cleavage Ce"
    _3_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "3-days post-L4 adult hermaphrodite Ce"
    _3_FOLD_EMBRYO_CE = "3-fold embryo Ce"
    _30_MIN_POST_FIRST_CLEAVAGE_CE = "30 min post first-cleavage Ce"
    _300_MIN_POST_FIRST_CLEAVAGE_CE = "300 min post first-cleavage Ce"
    _301_MIN_POST_FIRST_CLEAVAGE_CE = "301 min post first-cleavage Ce"
    _302_MIN_POST_FIRST_CLEAVAGE_CE = "302 min post first-cleavage Ce"
    _303_MIN_POST_FIRST_CLEAVAGE_CE = "303 min post first-cleavage Ce"
    _304_MIN_POST_FIRST_CLEAVAGE_CE = "304 min post first-cleavage Ce"
    _305_MIN_POST_FIRST_CLEAVAGE_CE = "305 min post first-cleavage Ce"
    _306_MIN_POST_FIRST_CLEAVAGE_CE = "306 min post first-cleavage Ce"
    _307_MIN_POST_FIRST_CLEAVAGE_CE = "307 min post first-cleavage Ce"
    _308_MIN_POST_FIRST_CLEAVAGE_CE = "308 min post first-cleavage Ce"
    _309_MIN_POST_FIRST_CLEAVAGE_CE = "309 min post first-cleavage Ce"
    _31_MIN_POST_FIRST_CLEAVAGE_CE = "31 min post first-cleavage Ce"
    _310_MIN_POST_FIRST_CLEAVAGE_CE = "310 min post first-cleavage Ce"
    _311_MIN_POST_FIRST_CLEAVAGE_CE = "311 min post first-cleavage Ce"
    _312_MIN_POST_FIRST_CLEAVAGE_CE = "312 min post first-cleavage Ce"
    _313_MIN_POST_FIRST_CLEAVAGE_CE = "313 min post first-cleavage Ce"
    _314_MIN_POST_FIRST_CLEAVAGE_CE = "314 min post first-cleavage Ce"
    _315_MIN_POST_FIRST_CLEAVAGE_CE = "315 min post first-cleavage Ce"
    _316_MIN_POST_FIRST_CLEAVAGE_CE = "316 min post first-cleavage Ce"
    _317_MIN_POST_FIRST_CLEAVAGE_CE = "317 min post first-cleavage Ce"
    _318_MIN_POST_FIRST_CLEAVAGE_CE = "318 min post first-cleavage Ce"
    _319_MIN_POST_FIRST_CLEAVAGE_CE = "319 min post first-cleavage Ce"
    _32_MIN_POST_FIRST_CLEAVAGE_CE = "32 min post first-cleavage Ce"
    _320_MIN_POST_FIRST_CLEAVAGE_CE = "320 min post first-cleavage Ce"
    _321_MIN_POST_FIRST_CLEAVAGE_CE = "321 min post first-cleavage Ce"
    _322_MIN_POST_FIRST_CLEAVAGE_CE = "322 min post first-cleavage Ce"
    _323_MIN_POST_FIRST_CLEAVAGE_CE = "323 min post first-cleavage Ce"
    _324_MIN_POST_FIRST_CLEAVAGE_CE = "324 min post first-cleavage Ce"
    _325_MIN_POST_FIRST_CLEAVAGE_CE = "325 min post first-cleavage Ce"
    _326_MIN_POST_FIRST_CLEAVAGE_CE = "326 min post first-cleavage Ce"
    _327_MIN_POST_FIRST_CLEAVAGE_CE = "327 min post first-cleavage Ce"
    _328_MIN_POST_FIRST_CLEAVAGE_CE = "328 min post first-cleavage Ce"
    _329_MIN_POST_FIRST_CLEAVAGE_CE = "329 min post first-cleavage Ce"
    _33_MIN_POST_FIRST_CLEAVAGE_CE = "33 min post first-cleavage Ce"
    _330_MIN_POST_FIRST_CLEAVAGE_CE = "330 min post first-cleavage Ce"
    _331_MIN_POST_FIRST_CLEAVAGE_CE = "331 min post first-cleavage Ce"
    _332_MIN_POST_FIRST_CLEAVAGE_CE = "332 min post first-cleavage Ce"
    _333_MIN_POST_FIRST_CLEAVAGE_CE = "333 min post first-cleavage Ce"
    _334_MIN_POST_FIRST_CLEAVAGE_CE = "334 min post first-cleavage Ce"
    _335_MIN_POST_FIRST_CLEAVAGE_CE = "335 min post first-cleavage Ce"
    _336_MIN_POST_FIRST_CLEAVAGE_CE = "336 min post first-cleavage Ce"
    _337_MIN_POST_FIRST_CLEAVAGE_CE = "337 min post first-cleavage Ce"
    _338_MIN_POST_FIRST_CLEAVAGE_CE = "338 min post first-cleavage Ce"
    _339_MIN_POST_FIRST_CLEAVAGE_CE = "339 min post first-cleavage Ce"
    _34_MIN_POST_FIRST_CLEAVAGE_CE = "34 min post first-cleavage Ce"
    _340_MIN_POST_FIRST_CLEAVAGE_CE = "340 min post first-cleavage Ce"
    _341_MIN_POST_FIRST_CLEAVAGE_CE = "341 min post first-cleavage Ce"
    _342_MIN_POST_FIRST_CLEAVAGE_CE = "342 min post first-cleavage Ce"
    _343_MIN_POST_FIRST_CLEAVAGE_CE = "343 min post first-cleavage Ce"
    _344_MIN_POST_FIRST_CLEAVAGE_CE = "344 min post first-cleavage Ce"
    _345_MIN_POST_FIRST_CLEAVAGE_CE = "345 min post first-cleavage Ce"
    _346_MIN_POST_FIRST_CLEAVAGE_CE = "346 min post first-cleavage Ce"
    _347_MIN_POST_FIRST_CLEAVAGE_CE = "347 min post first-cleavage Ce"
    _348_MIN_POST_FIRST_CLEAVAGE_CE = "348 min post first-cleavage Ce"
    _349_MIN_POST_FIRST_CLEAVAGE_CE = "349 min post first-cleavage Ce"
    _35_MIN_POST_FIRST_CLEAVAGE_CE = "35 min post first-cleavage Ce"
    _350_MIN_POST_FIRST_CLEAVAGE_CE = "350 min post first-cleavage Ce"
    _351_MIN_POST_FIRST_CLEAVAGE_CE = "351 min post first-cleavage Ce"
    _352_MIN_POST_FIRST_CLEAVAGE_CE = "352 min post first-cleavage Ce"
    _353_MIN_POST_FIRST_CLEAVAGE_CE = "353 min post first-cleavage Ce"
    _354_MIN_POST_FIRST_CLEAVAGE_CE = "354 min post first-cleavage Ce"
    _355_MIN_POST_FIRST_CLEAVAGE_CE = "355 min post first-cleavage Ce"
    _356_MIN_POST_FIRST_CLEAVAGE_CE = "356 min post first-cleavage Ce"
    _357_MIN_POST_FIRST_CLEAVAGE_CE = "357 min post first-cleavage Ce"
    _358_MIN_POST_FIRST_CLEAVAGE_CE = "358 min post first-cleavage Ce"
    _359_MIN_POST_FIRST_CLEAVAGE_CE = "359 min post first-cleavage Ce"
    _36_MIN_POST_FIRST_CLEAVAGE_CE = "36 min post first-cleavage Ce"
    _360_MIN_POST_FIRST_CLEAVAGE_CE = "360 min post first-cleavage Ce"
    _361_MIN_POST_FIRST_CLEAVAGE_CE = "361 min post first-cleavage Ce"
    _362_MIN_POST_FIRST_CLEAVAGE_CE = "362 min post first-cleavage Ce"
    _363_MIN_POST_FIRST_CLEAVAGE_CE = "363 min post first-cleavage Ce"
    _364_MIN_POST_FIRST_CLEAVAGE_CE = "364 min post first-cleavage Ce"
    _365_MIN_POST_FIRST_CLEAVAGE_CE = "365 min post first-cleavage Ce"
    _366_MIN_POST_FIRST_CLEAVAGE_CE = "366 min post first-cleavage Ce"
    _367_MIN_POST_FIRST_CLEAVAGE_CE = "367 min post first-cleavage Ce"
    _368_MIN_POST_FIRST_CLEAVAGE_CE = "368 min post first-cleavage Ce"
    _369_MIN_POST_FIRST_CLEAVAGE_CE = "369 min post first-cleavage Ce"
    _37_MIN_POST_FIRST_CLEAVAGE_CE = "37 min post first-cleavage Ce"
    _370_MIN_POST_FIRST_CLEAVAGE_CE = "370 min post first-cleavage Ce"
    _371_MIN_POST_FIRST_CLEAVAGE_CE = "371 min post first-cleavage Ce"
    _372_MIN_POST_FIRST_CLEAVAGE_CE = "372 min post first-cleavage Ce"
    _373_MIN_POST_FIRST_CLEAVAGE_CE = "373 min post first-cleavage Ce"
    _374_MIN_POST_FIRST_CLEAVAGE_CE = "374 min post first-cleavage Ce"
    _375_MIN_POST_FIRST_CLEAVAGE_CE = "375 min post first-cleavage Ce"
    _376_MIN_POST_FIRST_CLEAVAGE_CE = "376 min post first-cleavage Ce"
    _377_MIN_POST_FIRST_CLEAVAGE_CE = "377 min post first-cleavage Ce"
    _378_MIN_POST_FIRST_CLEAVAGE_CE = "378 min post first-cleavage Ce"
    _379_MIN_POST_FIRST_CLEAVAGE_CE = "379 min post first-cleavage Ce"
    _38_MIN_POST_FIRST_CLEAVAGE_CE = "38 min post first-cleavage Ce"
    _380_MIN_POST_FIRST_CLEAVAGE_CE = "380 min post first-cleavage Ce"
    _381_MIN_POST_FIRST_CLEAVAGE_CE = "381 min post first-cleavage Ce"
    _382_MIN_POST_FIRST_CLEAVAGE_CE = "382 min post first-cleavage Ce"
    _383_MIN_POST_FIRST_CLEAVAGE_CE = "383 min post first-cleavage Ce"
    _384_MIN_POST_FIRST_CLEAVAGE_CE = "384 min post first-cleavage Ce"
    _385_MIN_POST_FIRST_CLEAVAGE_CE = "385 min post first-cleavage Ce"
    _386_MIN_POST_FIRST_CLEAVAGE_CE = "386 min post first-cleavage Ce"
    _387_MIN_POST_FIRST_CLEAVAGE_CE = "387 min post first-cleavage Ce"
    _388_MIN_POST_FIRST_CLEAVAGE_CE = "388 min post first-cleavage Ce"
    _389_MIN_POST_FIRST_CLEAVAGE_CE = "389 min post first-cleavage Ce"
    _39_MIN_POST_FIRST_CLEAVAGE_CE = "39 min post first-cleavage Ce"
    _390_MIN_POST_FIRST_CLEAVAGE_CE = "390 min post first-cleavage Ce"
    _391_MIN_POST_FIRST_CLEAVAGE_CE = "391 min post first-cleavage Ce"
    _392_MIN_POST_FIRST_CLEAVAGE_CE = "392 min post first-cleavage Ce"
    _393_MIN_POST_FIRST_CLEAVAGE_CE = "393 min post first-cleavage Ce"
    _394_MIN_POST_FIRST_CLEAVAGE_CE = "394 min post first-cleavage Ce"
    _395_MIN_POST_FIRST_CLEAVAGE_CE = "395 min post first-cleavage Ce"
    _396_MIN_POST_FIRST_CLEAVAGE_CE = "396 min post first-cleavage Ce"
    _397_MIN_POST_FIRST_CLEAVAGE_CE = "397 min post first-cleavage Ce"
    _398_MIN_POST_FIRST_CLEAVAGE_CE = "398 min post first-cleavage Ce"
    _399_MIN_POST_FIRST_CLEAVAGE_CE = "399 min post first-cleavage Ce"
    _4_MIN_POST_FIRST_CLEAVAGE_CE = "4 min post first-cleavage Ce"
    _4_7_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "4-7 days post-L4 adult hermaphrodite Ce"
    _4_CELL_EMBRYO_CE = "4-cell embryo Ce"
    _4_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "4-days post-L4 adult hermaphrodite Ce"
    _40_MIN_POST_FIRST_CLEAVAGE_CE = "40 min post first-cleavage Ce"
    _400_MIN_POST_FIRST_CLEAVAGE_CE = "400 min post first-cleavage Ce"
    _401_MIN_POST_FIRST_CLEAVAGE_CE = "401 min post first-cleavage Ce"
    _402_MIN_POST_FIRST_CLEAVAGE_CE = "402 min post first-cleavage Ce"
    _403_MIN_POST_FIRST_CLEAVAGE_CE = "403 min post first-cleavage Ce"
    _404_MIN_POST_FIRST_CLEAVAGE_CE = "404 min post first-cleavage Ce"
    _405_MIN_POST_FIRST_CLEAVAGE_CE = "405 min post first-cleavage Ce"
    _406_MIN_POST_FIRST_CLEAVAGE_CE = "406 min post first-cleavage Ce"
    _407_MIN_POST_FIRST_CLEAVAGE_CE = "407 min post first-cleavage Ce"
    _408_MIN_POST_FIRST_CLEAVAGE_CE = "408 min post first-cleavage Ce"
    _409_MIN_POST_FIRST_CLEAVAGE_CE = "409 min post first-cleavage Ce"
    _41_MIN_POST_FIRST_CLEAVAGE_CE = "41 min post first-cleavage Ce"
    _410_MIN_POST_FIRST_CLEAVAGE_CE = "410 min post first-cleavage Ce"
    _411_MIN_POST_FIRST_CLEAVAGE_CE = "411 min post first-cleavage Ce"
    _412_MIN_POST_FIRST_CLEAVAGE_CE = "412 min post first-cleavage Ce"
    _413_MIN_POST_FIRST_CLEAVAGE_CE = "413 min post first-cleavage Ce"
    _414_MIN_POST_FIRST_CLEAVAGE_CE = "414 min post first-cleavage Ce"
    _415_MIN_POST_FIRST_CLEAVAGE_CE = "415 min post first-cleavage Ce"
    _416_MIN_POST_FIRST_CLEAVAGE_CE = "416 min post first-cleavage Ce"
    _417_MIN_POST_FIRST_CLEAVAGE_CE = "417 min post first-cleavage Ce"
    _418_MIN_POST_FIRST_CLEAVAGE_CE = "418 min post first-cleavage Ce"
    _419_MIN_POST_FIRST_CLEAVAGE_CE = "419 min post first-cleavage Ce"
    _42_MIN_POST_FIRST_CLEAVAGE_CE = "42 min post first-cleavage Ce"
    _420_MIN_POST_FIRST_CLEAVAGE_CE = "420 min post first-cleavage Ce"
    _421_MIN_POST_FIRST_CLEAVAGE_CE = "421 min post first-cleavage Ce"
    _422_MIN_POST_FIRST_CLEAVAGE_CE = "422 min post first-cleavage Ce"
    _423_MIN_POST_FIRST_CLEAVAGE_CE = "423 min post first-cleavage Ce"
    _424_MIN_POST_FIRST_CLEAVAGE_CE = "424 min post first-cleavage Ce"
    _425_MIN_POST_FIRST_CLEAVAGE_CE = "425 min post first-cleavage Ce"
    _426_MIN_POST_FIRST_CLEAVAGE_CE = "426 min post first-cleavage Ce"
    _427_MIN_POST_FIRST_CLEAVAGE_CE = "427 min post first-cleavage Ce"
    _428_MIN_POST_FIRST_CLEAVAGE_CE = "428 min post first-cleavage Ce"
    _429_MIN_POST_FIRST_CLEAVAGE_CE = "429 min post first-cleavage Ce"
    _43_MIN_POST_FIRST_CLEAVAGE_CE = "43 min post first-cleavage Ce"
    _430_MIN_POST_FIRST_CLEAVAGE_CE = "430 min post first-cleavage Ce"
    _431_MIN_POST_FIRST_CLEAVAGE_CE = "431 min post first-cleavage Ce"
    _432_MIN_POST_FIRST_CLEAVAGE_CE = "432 min post first-cleavage Ce"
    _433_MIN_POST_FIRST_CLEAVAGE_CE = "433 min post first-cleavage Ce"
    _434_MIN_POST_FIRST_CLEAVAGE_CE = "434 min post first-cleavage Ce"
    _435_MIN_POST_FIRST_CLEAVAGE_CE = "435 min post first-cleavage Ce"
    _436_MIN_POST_FIRST_CLEAVAGE_CE = "436 min post first-cleavage Ce"
    _437_MIN_POST_FIRST_CLEAVAGE_CE = "437 min post first-cleavage Ce"
    _438_MIN_POST_FIRST_CLEAVAGE_CE = "438 min post first-cleavage Ce"
    _439_MIN_POST_FIRST_CLEAVAGE_CE = "439 min post first-cleavage Ce"
    _44_MIN_POST_FIRST_CLEAVAGE_CE = "44 min post first-cleavage Ce"
    _44_CELL_EMBRYO_CE = "44-cell embryo Ce"
    _440_MIN_POST_FIRST_CLEAVAGE_CE = "440 min post first-cleavage Ce"
    _441_MIN_POST_FIRST_CLEAVAGE_CE = "441 min post first-cleavage Ce"
    _442_MIN_POST_FIRST_CLEAVAGE_CE = "442 min post first-cleavage Ce"
    _443_MIN_POST_FIRST_CLEAVAGE_CE = "443 min post first-cleavage Ce"
    _444_MIN_POST_FIRST_CLEAVAGE_CE = "444 min post first-cleavage Ce"
    _445_MIN_POST_FIRST_CLEAVAGE_CE = "445 min post first-cleavage Ce"
    _446_MIN_POST_FIRST_CLEAVAGE_CE = "446 min post first-cleavage Ce"
    _447_MIN_POST_FIRST_CLEAVAGE_CE = "447 min post first-cleavage Ce"
    _448_MIN_POST_FIRST_CLEAVAGE_CE = "448 min post first-cleavage Ce"
    _449_MIN_POST_FIRST_CLEAVAGE_CE = "449 min post first-cleavage Ce"
    _45_MIN_POST_FIRST_CLEAVAGE_CE = "45 min post first-cleavage Ce"
    _450_MIN_POST_FIRST_CLEAVAGE_CE = "450 min post first-cleavage Ce"
    _451_MIN_POST_FIRST_CLEAVAGE_CE = "451 min post first-cleavage Ce"
    _452_MIN_POST_FIRST_CLEAVAGE_CE = "452 min post first-cleavage Ce"
    _453_MIN_POST_FIRST_CLEAVAGE_CE = "453 min post first-cleavage Ce"
    _454_MIN_POST_FIRST_CLEAVAGE_CE = "454 min post first-cleavage Ce"
    _455_MIN_POST_FIRST_CLEAVAGE_CE = "455 min post first-cleavage Ce"
    _456_MIN_POST_FIRST_CLEAVAGE_CE = "456 min post first-cleavage Ce"
    _457_MIN_POST_FIRST_CLEAVAGE_CE = "457 min post first-cleavage Ce"
    _458_MIN_POST_FIRST_CLEAVAGE_CE = "458 min post first-cleavage Ce"
    _459_MIN_POST_FIRST_CLEAVAGE_CE = "459 min post first-cleavage Ce"
    _46_MIN_POST_FIRST_CLEAVAGE_CE = "46 min post first-cleavage Ce"
    _460_MIN_POST_FIRST_CLEAVAGE_CE = "460 min post first-cleavage Ce"
    _461_MIN_POST_FIRST_CLEAVAGE_CE = "461 min post first-cleavage Ce"
    _462_MIN_POST_FIRST_CLEAVAGE_CE = "462 min post first-cleavage Ce"
    _463_MIN_POST_FIRST_CLEAVAGE_CE = "463 min post first-cleavage Ce"
    _464_MIN_POST_FIRST_CLEAVAGE_CE = "464 min post first-cleavage Ce"
    _465_MIN_POST_FIRST_CLEAVAGE_CE = "465 min post first-cleavage Ce"
    _466_MIN_POST_FIRST_CLEAVAGE_CE = "466 min post first-cleavage Ce"
    _467_MIN_POST_FIRST_CLEAVAGE_CE = "467 min post first-cleavage Ce"
    _468_MIN_POST_FIRST_CLEAVAGE_CE = "468 min post first-cleavage Ce"
    _469_MIN_POST_FIRST_CLEAVAGE_CE = "469 min post first-cleavage Ce"
    _47_MIN_POST_FIRST_CLEAVAGE_CE = "47 min post first-cleavage Ce"
    _470_MIN_POST_FIRST_CLEAVAGE_CE = "470 min post first-cleavage Ce"
    _471_MIN_POST_FIRST_CLEAVAGE_CE = "471 min post first-cleavage Ce"
    _472_MIN_POST_FIRST_CLEAVAGE_CE = "472 min post first-cleavage Ce"
    _473_MIN_POST_FIRST_CLEAVAGE_CE = "473 min post first-cleavage Ce"
    _474_MIN_POST_FIRST_CLEAVAGE_CE = "474 min post first-cleavage Ce"
    _475_MIN_POST_FIRST_CLEAVAGE_CE = "475 min post first-cleavage Ce"
    _476_MIN_POST_FIRST_CLEAVAGE_CE = "476 min post first-cleavage Ce"
    _477_MIN_POST_FIRST_CLEAVAGE_CE = "477 min post first-cleavage Ce"
    _478_MIN_POST_FIRST_CLEAVAGE_CE = "478 min post first-cleavage Ce"
    _479_MIN_POST_FIRST_CLEAVAGE_CE = "479 min post first-cleavage Ce"
    _48_MIN_POST_FIRST_CLEAVAGE_CE = "48 min post first-cleavage Ce"
    _480_MIN_POST_FIRST_CLEAVAGE_CE = "480 min post first-cleavage Ce"
    _481_MIN_POST_FIRST_CLEAVAGE_CE = "481 min post first-cleavage Ce"
    _482_MIN_POST_FIRST_CLEAVAGE_CE = "482 min post first-cleavage Ce"
    _483_MIN_POST_FIRST_CLEAVAGE_CE = "483 min post first-cleavage Ce"
    _484_MIN_POST_FIRST_CLEAVAGE_CE = "484 min post first-cleavage Ce"
    _485_MIN_POST_FIRST_CLEAVAGE_CE = "485 min post first-cleavage Ce"
    _486_MIN_POST_FIRST_CLEAVAGE_CE = "486 min post first-cleavage Ce"
    _487_MIN_POST_FIRST_CLEAVAGE_CE = "487 min post first-cleavage Ce"
    _488_MIN_POST_FIRST_CLEAVAGE_CE = "488 min post first-cleavage Ce"
    _489_MIN_POST_FIRST_CLEAVAGE_CE = "489 min post first-cleavage Ce"
    _49_MIN_POST_FIRST_CLEAVAGE_CE = "49 min post first-cleavage Ce"
    _490_MIN_POST_FIRST_CLEAVAGE_CE = "490 min post first-cleavage Ce"
    _491_MIN_POST_FIRST_CLEAVAGE_CE = "491 min post first-cleavage Ce"
    _492_MIN_POST_FIRST_CLEAVAGE_CE = "492 min post first-cleavage Ce"
    _493_MIN_POST_FIRST_CLEAVAGE_CE = "493 min post first-cleavage Ce"
    _494_MIN_POST_FIRST_CLEAVAGE_CE = "494 min post first-cleavage Ce"
    _495_MIN_POST_FIRST_CLEAVAGE_CE = "495 min post first-cleavage Ce"
    _496_MIN_POST_FIRST_CLEAVAGE_CE = "496 min post first-cleavage Ce"
    _497_MIN_POST_FIRST_CLEAVAGE_CE = "497 min post first-cleavage Ce"
    _498_MIN_POST_FIRST_CLEAVAGE_CE = "498 min post first-cleavage Ce"
    _499_MIN_POST_FIRST_CLEAVAGE_CE = "499 min post first-cleavage Ce"
    _5_MIN_POST_FIRST_CLEAVAGE_CE = "5 min post first-cleavage Ce"
    _5_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "5-days post-L4 adult hermaphrodite Ce"
    _50_MIN_POST_FIRST_CLEAVAGE_CE = "50 min post first-cleavage Ce"
    _500_MIN_POST_FIRST_CLEAVAGE_CE = "500 min post first-cleavage Ce"
    _501_MIN_POST_FIRST_CLEAVAGE_CE = "501 min post first-cleavage Ce"
    _502_MIN_POST_FIRST_CLEAVAGE_CE = "502 min post first-cleavage Ce"
    _503_MIN_POST_FIRST_CLEAVAGE_CE = "503 min post first-cleavage Ce"
    _504_MIN_POST_FIRST_CLEAVAGE_CE = "504 min post first-cleavage Ce"
    _505_MIN_POST_FIRST_CLEAVAGE_CE = "505 min post first-cleavage Ce"
    _506_MIN_POST_FIRST_CLEAVAGE_CE = "506 min post first-cleavage Ce"
    _507_MIN_POST_FIRST_CLEAVAGE_CE = "507 min post first-cleavage Ce"
    _508_MIN_POST_FIRST_CLEAVAGE_CE = "508 min post first-cleavage Ce"
    _509_MIN_POST_FIRST_CLEAVAGE_CE = "509 min post first-cleavage Ce"
    _51_MIN_POST_FIRST_CLEAVAGE_CE = "51 min post first-cleavage Ce"
    _51_CELL_EMBRYO_CE = "51-cell embryo Ce"
    _510_MIN_POST_FIRST_CLEAVAGE_CE = "510 min post first-cleavage Ce"
    _511_MIN_POST_FIRST_CLEAVAGE_CE = "511 min post first-cleavage Ce"
    _512_MIN_POST_FIRST_CLEAVAGE_CE = "512 min post first-cleavage Ce"
    _513_MIN_POST_FIRST_CLEAVAGE_CE = "513 min post first-cleavage Ce"
    _514_MIN_POST_FIRST_CLEAVAGE_CE = "514 min post first-cleavage Ce"
    _515_MIN_POST_FIRST_CLEAVAGE_CE = "515 min post first-cleavage Ce"
    _516_MIN_POST_FIRST_CLEAVAGE_CE = "516 min post first-cleavage Ce"
    _517_MIN_POST_FIRST_CLEAVAGE_CE = "517 min post first-cleavage Ce"
    _518_MIN_POST_FIRST_CLEAVAGE_CE = "518 min post first-cleavage Ce"
    _519_MIN_POST_FIRST_CLEAVAGE_CE = "519 min post first-cleavage Ce"
    _52_MIN_POST_FIRST_CLEAVAGE_CE = "52 min post first-cleavage Ce"
    _520_MIN_POST_FIRST_CLEAVAGE_CE = "520 min post first-cleavage Ce"
    _521_MIN_POST_FIRST_CLEAVAGE_CE = "521 min post first-cleavage Ce"
    _522_MIN_POST_FIRST_CLEAVAGE_CE = "522 min post first-cleavage Ce"
    _523_MIN_POST_FIRST_CLEAVAGE_CE = "523 min post first-cleavage Ce"
    _524_MIN_POST_FIRST_CLEAVAGE_CE = "524 min post first-cleavage Ce"
    _525_MIN_POST_FIRST_CLEAVAGE_CE = "525 min post first-cleavage Ce"
    _526_MIN_POST_FIRST_CLEAVAGE_CE = "526 min post first-cleavage Ce"
    _527_MIN_POST_FIRST_CLEAVAGE_CE = "527 min post first-cleavage Ce"
    _528_MIN_POST_FIRST_CLEAVAGE_CE = "528 min post first-cleavage Ce"
    _529_MIN_POST_FIRST_CLEAVAGE_CE = "529 min post first-cleavage Ce"
    _53_MIN_POST_FIRST_CLEAVAGE_CE = "53 min post first-cleavage Ce"
    _530_MIN_POST_FIRST_CLEAVAGE_CE = "530 min post first-cleavage Ce"
    _531_MIN_POST_FIRST_CLEAVAGE_CE = "531 min post first-cleavage Ce"
    _532_MIN_POST_FIRST_CLEAVAGE_CE = "532 min post first-cleavage Ce"
    _533_MIN_POST_FIRST_CLEAVAGE_CE = "533 min post first-cleavage Ce"
    _534_MIN_POST_FIRST_CLEAVAGE_CE = "534 min post first-cleavage Ce"
    _535_MIN_POST_FIRST_CLEAVAGE_CE = "535 min post first-cleavage Ce"
    _536_MIN_POST_FIRST_CLEAVAGE_CE = "536 min post first-cleavage Ce"
    _537_MIN_POST_FIRST_CLEAVAGE_CE = "537 min post first-cleavage Ce"
    _538_MIN_POST_FIRST_CLEAVAGE_CE = "538 min post first-cleavage Ce"
    _539_MIN_POST_FIRST_CLEAVAGE_CE = "539 min post first-cleavage Ce"
    _54_MIN_POST_FIRST_CLEAVAGE_CE = "54 min post first-cleavage Ce"
    _540_MIN_POST_FIRST_CLEAVAGE_CE = "540 min post first-cleavage Ce"
    _541_MIN_POST_FIRST_CLEAVAGE_CE = "541 min post first-cleavage Ce"
    _542_MIN_POST_FIRST_CLEAVAGE_CE = "542 min post first-cleavage Ce"
    _543_MIN_POST_FIRST_CLEAVAGE_CE = "543 min post first-cleavage Ce"
    _544_MIN_POST_FIRST_CLEAVAGE_CE = "544 min post first-cleavage Ce"
    _545_MIN_POST_FIRST_CLEAVAGE_CE = "545 min post first-cleavage Ce"
    _546_MIN_POST_FIRST_CLEAVAGE_CE = "546 min post first-cleavage Ce"
    _547_MIN_POST_FIRST_CLEAVAGE_CE = "547 min post first-cleavage Ce"
    _548_MIN_POST_FIRST_CLEAVAGE_CE = "548 min post first-cleavage Ce"
    _549_MIN_POST_FIRST_CLEAVAGE_CE = "549 min post first-cleavage Ce"
    _55_MIN_POST_FIRST_CLEAVAGE_CE = "55 min post first-cleavage Ce"
    _550_MIN_POST_FIRST_CLEAVAGE_CE = "550 min post first-cleavage Ce"
    _56_MIN_POST_FIRST_CLEAVAGE_CE = "56 min post first-cleavage Ce"
    _560_MIN_POST_FIRST_CLEAVAGE_CE = "560 min post first-cleavage Ce"
    _57_MIN_POST_FIRST_CLEAVAGE_CE = "57 min post first-cleavage Ce"
    _570_MIN_POST_FIRST_CLEAVAGE_CE = "570 min post first-cleavage Ce"
    _58_MIN_POST_FIRST_CLEAVAGE_CE = "58 min post first-cleavage Ce"
    _59_MIN_POST_FIRST_CLEAVAGE_CE = "59 min post first-cleavage Ce"
    _6_MIN_POST_FIRST_CLEAVAGE_CE = "6 min post first-cleavage Ce"
    _6_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "6-days post-L4 adult hermaphrodite Ce"
    _60_MIN_POST_FIRST_CLEAVAGE_CE = "60 min post first-cleavage Ce"
    _61_MIN_POST_FIRST_CLEAVAGE_CE = "61 min post first-cleavage Ce"
    _62_MIN_POST_FIRST_CLEAVAGE_CE = "62 min post first-cleavage Ce"
    _63_MIN_POST_FIRST_CLEAVAGE_CE = "63 min post first-cleavage Ce"
    _64_MIN_POST_FIRST_CLEAVAGE_CE = "64 min post first-cleavage Ce"
    _640_MIN_POST_FIRST_CLEAVAGE_CE = "640 min post first-cleavage Ce"
    _65_MIN_POST_FIRST_CLEAVAGE_CE = "65 min post first-cleavage Ce"
    _650_MIN_POST_FIRST_CLEAVAGE_CE = "650 min post first-cleavage Ce"
    _66_MIN_POST_FIRST_CLEAVAGE_CE = "66 min post first-cleavage Ce"
    _660_MIN_POST_FIRST_CLEAVAGE_CE = "660 min post first-cleavage Ce"
    _67_MIN_POST_FIRST_CLEAVAGE_CE = "67 min post first-cleavage Ce"
    _68_MIN_POST_FIRST_CLEAVAGE_CE = "68 min post first-cleavage Ce"
    _68_CELL_EMBRYO_CE = "68-cell embryo Ce"
    _69_MIN_POST_FIRST_CLEAVAGE_CE = "69 min post first-cleavage Ce"
    _7_MIN_POST_FIRST_CLEAVAGE_CE = "7 min post first-cleavage Ce"
    _7_10_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "7-10 days post-L4 adult hermaphrodite Ce"
    _7_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "7-days post-L4 adult hermaphrodite Ce"
    _70_MIN_POST_FIRST_CLEAVAGE_CE = "70 min post first-cleavage Ce"
    _71_MIN_POST_FIRST_CLEAVAGE_CE = "71 min post first-cleavage Ce"
    _72_MIN_POST_FIRST_CLEAVAGE_CE = "72 min post first-cleavage Ce"
    _720_MIN_POST_FIRST_CLEAVAGE_CE = "720 min post first-cleavage Ce"
    _73_MIN_POST_FIRST_CLEAVAGE_CE = "73 min post first-cleavage Ce"
    _74_MIN_POST_FIRST_CLEAVAGE_CE = "74 min post first-cleavage Ce"
    _75_MIN_POST_FIRST_CLEAVAGE_CE = "75 min post first-cleavage Ce"
    _76_MIN_POST_FIRST_CLEAVAGE_CE = "76 min post first-cleavage Ce"
    _77_MIN_POST_FIRST_CLEAVAGE_CE = "77 min post first-cleavage Ce"
    _770_MIN_POST_FIRST_CLEAVAGE_CE = "770 min post first-cleavage Ce"
    _78_MIN_POST_FIRST_CLEAVAGE_CE = "78 min post first-cleavage Ce"
    _780_MIN_POST_FIRST_CLEAVAGE_CE = "780 min post first-cleavage Ce"
    _79_MIN_POST_FIRST_CLEAVAGE_CE = "79 min post first-cleavage Ce"
    _8_MIN_POST_FIRST_CLEAVAGE_CE = "8 min post first-cleavage Ce"
    _8_CELL_EMBRYO_CE = "8-cell embryo Ce"
    _8_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "8-days post-L4 adult hermaphrodite Ce"
    _80_MIN_POST_FIRST_CLEAVAGE_CE = "80 min post first-cleavage Ce"
    _81_MIN_POST_FIRST_CLEAVAGE_CE = "81 min post first-cleavage Ce"
    _82_MIN_POST_FIRST_CLEAVAGE_CE = "82 min post first-cleavage Ce"
    _820_MIN_POST_FIRST_CLEAVAGE_CE = "820 min post first-cleavage Ce"
    _83_MIN_POST_FIRST_CLEAVAGE_CE = "83 min post first-cleavage Ce"
    _830_MIN_POST_FIRST_CLEAVAGE_CE = "830 min post first-cleavage Ce"
    _84_MIN_POST_FIRST_CLEAVAGE_CE = "84 min post first-cleavage Ce"
    _85_MIN_POST_FIRST_CLEAVAGE_CE = "85 min post first-cleavage Ce"
    _850_MIN_POST_FIRST_CLEAVAGE_CE = "850 min post first-cleavage Ce"
    _86_MIN_POST_FIRST_CLEAVAGE_CE = "86 min post first-cleavage Ce"
    _86_CELL_EMBRYO_CE = "86-cell embryo Ce"
    _87_MIN_POST_FIRST_CLEAVAGE_CE = "87 min post first-cleavage Ce"
    _88_MIN_POST_FIRST_CLEAVAGE_CE = "88 min post first-cleavage Ce"
    _88_CELL_EMBRYO_CE = "88-cell embryo Ce"
    _89_MIN_POST_FIRST_CLEAVAGE_CE = "89 min post first-cleavage Ce"
    _9_MIN_POST_FIRST_CLEAVAGE_CE = "9 min post first-cleavage Ce"
    _9_DAYS_POST_L4_ADULT_HERMAPHRODITE_CE = "9-days post-L4 adult hermaphrodite Ce"
    _90_MIN_POST_FIRST_CLEAVAGE_CE = "90 min post first-cleavage Ce"
    _91_MIN_POST_FIRST_CLEAVAGE_CE = "91 min post first-cleavage Ce"
    _92_MIN_POST_FIRST_CLEAVAGE_CE = "92 min post first-cleavage Ce"
    _93_MIN_POST_FIRST_CLEAVAGE_CE = "93 min post first-cleavage Ce"
    _94_MIN_POST_FIRST_CLEAVAGE_CE = "94 min post first-cleavage Ce"
    _95_MIN_POST_FIRST_CLEAVAGE_CE = "95 min post first-cleavage Ce"
    _96_MIN_POST_FIRST_CLEAVAGE_CE = "96 min post first-cleavage Ce"
    _96_CELL_EMBRYO_CE = "96-cell embryo Ce"
    _97_MIN_POST_FIRST_CLEAVAGE_CE = "97 min post first-cleavage Ce"
    _98_MIN_POST_FIRST_CLEAVAGE_CE = "98 min post first-cleavage Ce"
    _99_MIN_POST_FIRST_CLEAVAGE_CE = "99 min post first-cleavage Ce"
    BRUGIA_L1 = "Brugia L1"
    BRUGIA_L2 = "Brugia L2"
    BRUGIA_L3 = "Brugia L3"
    BRUGIA_L3I = "Brugia L3i"
    BRUGIA_L4 = "Brugia L4"
    BRUGIA_ADULT = "Brugia adult"
    BRUGIA_EARLY_EMBRYO = "Brugia early embryo"
    BRUGIA_EMBRYO = "Brugia embryo"
    BRUGIA_LARVAL_STAGE = "Brugia larval stage"
    BRUGIA_LATE_EMBRYO = "Brugia late embryo"
    BRUGIA_LIFE_STAGE = "Brugia life stage"
    BRUGIA_MICROFILARIA = "Brugia microfilaria"
    BRUGIA_MIDDLE_EMBRYO = "Brugia middle embryo"
    BRUGIA_POST_INFECTION_L3 = "Brugia post-infection L3"
    BRUGIA_POSTEMBRYONIC_STAGE = "Brugia postembryonic stage"
    BRUGIA_SHEATHED_MICROFILARIA = "Brugia sheathed microfilaria"
    BRUGIA_UNSHEATHED_MICROFILARIA = "Brugia unsheathed microfilaria"
    BRUGIA_YOUNG_ADULT = "Brugia young adult"
    C__ELEGANS_LIFE_STAGE = "C. elegans life stage"
    C__ELEGANS_LIFE_STAGE_BY_MINUTES_POST_FIRST_CLEAVAGE = "C. elegans life stage by minutes post first cleavage"
    C__ELEGANS_LIFE_STAGE_BY_NUMBER_OF_CELLS = "C. elegans life stage by number of cells"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_1_5_FOLD_EMBRYO = "C. elegans life stage occurring during 1.5-fold embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_2_FOLD_EMBRYO = "C. elegans life stage occurring during 2-fold embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_3_FOLD_EMBRYO = "C. elegans life stage occurring during 3-fold embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_L1_LARVAL_STAGE = "C. elegans life stage occurring during L1 larval stage"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_L2_LARVAL_STAGE = "C. elegans life stage occurring during L2 larval stage"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_L3_LARVAL_STAGE = "C. elegans life stage occurring during L3 larval stage"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_L4_LARVAL_STAGE = "C. elegans life stage occurring during L4 larval stage"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_ADULTHOOD = "C. elegans life stage occurring during adulthood"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_BEAN_EMBRYO = "C. elegans life stage occurring during bean embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_BLASTULA_EMBRYO = "C. elegans life stage occurring during blastula embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_COMMA_EMBRYO = "C. elegans life stage occurring during comma embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_ELONGATING_EMBRYO = (
        "C. elegans life stage occurring during elongating embryo"
    )
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_EMBRYOGENESIS = "C. elegans life stage occurring during embryogenesis"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_ENCLOSING_EMBRYO = "C. elegans life stage occurring during enclosing embryo"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_FULLY_ELONGATED_EMBRYO = (
        "C. elegans life stage occurring during fully-elongated embryo"
    )
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_GASTRULATION = "C. elegans life stage occurring during gastrulation"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_LARVAL_MOLT = "C. elegans life stage occurring during larval molt"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_LARVAL_STAGE = "C. elegans life stage occurring during larval stage"
    C__ELEGANS_LIFE_STAGE_OCCURRING_DURING_PROLIFERATING_EMBRYO = (
        "C. elegans life stage occurring during proliferating embryo"
    )
    C__ELEGANS_LIFE_STAGE_OCCURRING_POST_EMBRYOGENESIS = "C. elegans life stage occurring post embryogenesis"
    CESTODA_LIFE_STAGE = "Cestoda life stage"
    DIGENEAN_LIFE_STAGE = "Digenean life stage"
    L1_ARREST_CE = "L1 arrest Ce"
    L1_LARVA_CE = "L1 larva Ce"
    L1_LARVAL_STAGE = "L1 larval stage"
    L1_L2_ECDYSIS_CE = "L1-L2 ecdysis Ce"
    L1_L2_LETHARGUS_CE = "L1-L2 lethargus Ce"
    L1_L2_MOLT_CE = "L1-L2 molt Ce"
    L1_L2D_ECDYSIS_CE = "L1-L2d ecdysis Ce"
    L1_L2D_LETHARGUS_CE = "L1-L2d lethargus Ce"
    L1_L2D_MOLT_CE = "L1-L2d molt Ce"
    L2_LARVA_CE = "L2 larva Ce"
    L2_LARVAL_STAGE = "L2 larval stage"
    L2_L3_ECDYSIS_CE = "L2-L3 ecdysis Ce"
    L2_L3_LETHARGUS_CE = "L2-L3 lethargus Ce"
    L2_L3_MOLT_CE = "L2-L3 molt Ce"
    L2D_LARVA_CE = "L2d larva Ce"
    L2D_L3_ECDYSIS_CE = "L2d-L3 ecdysis Ce"
    L2D_L3_LETHARGUS_CE = "L2d-L3 lethargus Ce"
    L2D_L3_MOLT_CE = "L2d-L3 molt Ce"
    L2D_DAUER_ECDYSIS_CE = "L2d-dauer ecdysis Ce"
    L2D_DAUER_LETHARGUS_CE = "L2d-dauer lethargus Ce"
    L2D_DAUER_MOLT_CE = "L2d-dauer molt Ce"
    L3_LARVA_CE = "L3 larva Ce"
    L3_LARVAL_STAGE = "L3 larval stage"
    L3_L4_ECDYSIS_CE = "L3-L4 ecdysis Ce"
    L3_L4_LETHARGUS_CE = "L3-L4 lethargus Ce"
    L3_L4_MOLT_CE = "L3-L4 molt Ce"
    L4_LARVA_CE = "L4 larva Ce"
    L4_LARVA_MALE_CE = "L4 larva male Ce"
    L4_LARVAL_STAGE = "L4 larval stage"
    L4_ADULT_ECDYSIS_CE = "L4-adult ecdysis Ce"
    L4_ADULT_LETHARGUS_CE = "L4-adult lethargus Ce"
    L4_ADULT_MOLT_CE = "L4-adult molt Ce"
    L4_0_LARVA_CE = "L4.0 larva Ce"
    L4_1_LARVA_CE = "L4.1 larva Ce"
    L4_2_LARVA_CE = "L4.2 larva Ce"
    L4_3_LARVA_CE = "L4.3 larva Ce"
    L4_4_LARVA_CE = "L4.4 larva Ce"
    L4_5_LARVA_CE = "L4.5 larva Ce"
    L4_6_LARVA_CE = "L4.6 larva Ce"
    L4_7_LARVA_CE = "L4.7 larva Ce"
    L4_8_LARVA_CE = "L4.8 larva Ce"
    L4_9_LARVA_CE = "L4.9 larva Ce"
    NEMATODE_LIFE_STAGE = "Nematode life stage"
    ONCHOCERCA_L1_LARVA = "Onchocerca L1 larva"
    ONCHOCERCA_L2_LARVA = "Onchocerca L2 larva"
    ONCHOCERCA_L3_LARVA__MAMMALIAN_STAGE_ = "Onchocerca L3 larva (mammalian stage)"
    ONCHOCERCA_L3_LARVA__VECTOR_STAGE_ = "Onchocerca L3 larva (vector stage)"
    ONCHOCERCA_L3_LARVA_IN_VITRO_CULTURED_D1 = "Onchocerca L3 larva in vitro cultured D1"
    ONCHOCERCA_L3_LARVA_IN_VITRO_CULTURED_D2 = "Onchocerca L3 larva in vitro cultured D2"
    ONCHOCERCA_L3_LARVA_IN_VITRO_CULTURED_D3 = "Onchocerca L3 larva in vitro cultured D3"
    ONCHOCERCA_L4_LARVA = "Onchocerca L4 larva"
    ONCHOCERCA_L4_LARVA_IN_VITRO_CULTURED = "Onchocerca L4 larva in vitro cultured"
    ONCHOCERCA_ADULT_FEMALE = "Onchocerca adult female"
    ONCHOCERCA_ADULT_MALE = "Onchocerca adult male"
    ONCHOCERCA_EMBRYONIC_LIFE_STAGE = "Onchocerca embryonic life stage"
    ONCHOCERCA_LIFE_STAGE = "Onchocerca life stage"
    ONCHOCERCA_MICROFILARIA__MAMMALIAN_STAGE_ = "Onchocerca microfilaria (mammalian stage)"
    ONCHOCERCA_MICROFILARIA__VECTOR_STAGE_ = "Onchocerca microfilaria (vector stage)"
    ONCHOCERCA_POST_EMBRYONIC_LIFE_STAGE = "Onchocerca post-embryonic life stage"
    PLATYHELMINTHES_ADULT = "Platyhelminthes adult"
    PLATYHELMINTHES_EGG = "Platyhelminthes egg"
    PLATYHELMINTHES_LIFE_STAGE = "Platyhelminthes life stage"
    STRONGYLOIDES_FREE_LIVING_ADULT_FEMALE = "Strongyloides free living adult female"
    STRONGYLOIDES_FREE_LIVING_ADULT_MALE = "Strongyloides free living adult male"
    STRONGYLOIDES_FREE_LIVING_ADULT = "Strongyloides free-living adult"
    STRONGYLOIDES_FREE_LIVING_STAGE = "Strongyloides free-living stage"
    STRONGYLOIDES_INFECTIVE_L3 = "Strongyloides infective L3"
    STRONGYLOIDES_LIFE_STAGE = "Strongyloides life stage"
    STRONGYLOIDES_PARASITIC_FEMALE = "Strongyloides parasitic female"
    STRONGYLOIDES_PARASITIC_STAGE = "Strongyloides parasitic stage"
    STRONGYLOIDES_POST_FREE_LIVING_L1 = "Strongyloides post free-living L1"
    STRONGYLOIDES_POST_FREE_LIVING_L3 = "Strongyloides post free-living L3"
    STRONGYLOIDES_POST_PARASITIC_L1 = "Strongyloides post parasitic L1"
    STRONGYLOIDES_POST_PARASITIC_L3 = "Strongyloides post parasitic L3"
    ADULT_CE = "adult Ce"
    ADULT_HERMAPHRODITE_CE = "adult hermaphrodite Ce"
    ADULT_MALE_CE = "adult male Ce"
    ALL_STAGES_CE = "all stages Ce"
    BEAN_EMBRYO_CE = "bean embryo Ce"
    BLASTULA_EMBRYO_CE = "blastula embryo Ce"
    CERCARIUM = "cercarium"
    COMMA_EMBRYO_CE = "comma embryo Ce"
    CYSTICERCOID_STAGE = "cysticercoid stage"
    DAUER_LARVA_CE = "dauer larva Ce"
    ELONGATING_EMBRYO_CE = "elongating embryo Ce"
    EMBRYO_CE = "embryo Ce"
    ENCLOSING_EMBRYO_CE = "enclosing embryo Ce"
    FREE_LIVING_NEMATODE_STAGE = "free-living nematode stage"
    FULLY_ELONGATED_EMBRYO_CE = "fully-elongated embryo Ce"
    GASTRULATING_EMBRYO_CE = "gastrulating embryo Ce"
    HYDATID_CYST_STAGE = "hydatid cyst stage"
    JUVENILE_FLUKE = "juvenile fluke"
    LARVA_CE = "larva Ce"
    LATE_CLEAVAGE_STAGE_EMBRYO_CE = "late cleavage stage embryo Ce"
    METACERCARIUM = "metacercarium"
    METACESTODE = "metacestode"
    MICROFILARIA = "microfilaria"
    MIRACIDIUM = "miracidium"
    NEMATODE_ADULT = "nematode adult"
    NEMATODE_EMBRYO = "nematode embryo"
    NEMATODE_INFECTIVE_STAGE_LARVA = "nematode infective stage larva"
    NEMATODE_LARVAL_STAGE = "nematode larval stage"
    NEWLY_EXCYSTED_JUVENILES = "newly excysted juveniles"
    NEWLY_HATCHED_L1_LARVAL_STAGE_CE = "newly hatched L1 larval stage Ce"
    NEWLY_MOLTED_YOUNG_ADULT_HERMAPHRODITE_CE = "newly molted young adult hermaphrodite Ce"
    NODULAR_MICROFILARIA = "nodular microfilaria"
    ONCOSPHERE = "oncosphere"
    OOCYTE_LAYING_STAGE_ADULT_HERMAPHRODITE_CE = "oocyte-laying stage adult hermaphrodite Ce"
    PARASITIC_NEMATODE_STAGE = "parasitic nematode stage"
    POST_DAUER_L3_STAGE_CE = "post dauer L3 stage Ce"
    POST_DAUER_L4_STAGE_CE = "post dauer L4 stage Ce"
    POST_DAUER_ADULT_STAGE_CE = "post dauer adult stage Ce"
    POST_DAUER_STAGE_CE = "post dauer stage Ce"
    POST_REPRODUCTIVE_STAGE_ADULT_HERMAPHRODITE_CE = "post-reproductive stage adult hermaphrodite Ce"
    POSTDAUER_L4_ECDYSIS_CE = "postdauer-L4 ecdysis Ce"
    POSTDAUER_L4_LETHARGUS_CE = "postdauer-L4 lethargus Ce"
    POSTDAUER_L4_MOLT_CE = "postdauer-L4 molt Ce"
    POSTEMBRYONIC_CE = "postembryonic Ce"
    POSTEMBRYONIC_NEMATODE = "postembryonic nematode"
    PRE_REPRODUCTIVE_STAGE_ADULT_HERMAPHRODITE_CE = "pre-reproductive stage adult hermaphrodite Ce"
    PROLIFERATING_EMBRYO_CE = "proliferating embryo Ce"
    PROTOSCOLEX_STAGE = "protoscolex stage"
    REPRODUCTIVE_STAGE_ADULT_HERMAPHRODITE_CE = "reproductive stage adult hermaphrodite Ce"
    SCHISTOSOMULUM = "schistosomulum"
    SHEATHED_MICROFILARIA = "sheathed microfilaria"
    SKIN_MICROFILARIA = "skin microfilaria"
    SPOROCYST = "sporocyst"
    UNFERTILIZED_EGG_CE = "unfertilized egg Ce"
    UNSHEATHED_MICROFILARIA = "unsheathed microfilaria"
    WORM_LIFE_STAGE = "worm life stage"
